version: '3'

services:

  mysql: 
    image: library/mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: classmate

  backend:
    build: .
    ports:
      - 5333:5333
    depends_on: 
      - mysql
    links:
      - mysql
    env_file:
      - docker.env
